#pragma once

#include <RTNeural/RTNeural.h>

#include <algorithm>
#include <array>
#include <atomic>
#include <cmath>
#include <functional>
#include <map>
#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/pose.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "neural_controller/cem_phase_controller.hpp"
#include "neural_controller/command_encoding.hpp"
#include "neural_controller/rolling_history.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.hpp"
#include "realtime_tools/realtime_publisher.hpp"
#include "std_msgs/msg/empty.hpp"
#include "std_msgs/msg/float32.hpp"
#include "std_msgs/msg/float32_multi_array.hpp"
#include "std_msgs/msg/string.hpp"
#include <chrono>
#include "tf2/LinearMath/Matrix3x3.h"
#include "tf2/LinearMath/Quaternion.h"
// auto-generated by generate_parameter_library
#include <neural_controller/neural_controller_parameters.hpp>

namespace neural_controller {

template <typename T>
bool contains_non_finite(const T &container) {
  return std::any_of(container.begin(), container.end(),
                     [](double val) { return !std::isfinite(val); });
}

class NeuralController : public controller_interface::ControllerInterface {
 public:
  NeuralController();

  ~NeuralController() = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::CallbackReturn on_error(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::return_type update(const rclcpp::Time &time,
                                           const rclcpp::Duration &period) override;

 protected:
  bool check_param_vector_size();

  controller_interface::return_type update_cem(const rclcpp::Time &time,
                                                const rclcpp::Duration &period,
                                                double elapsed_s);

  void update_roll_to_stand(double pitch, double pitch_rate, double elapsed_s);
  void load_neural_roll_to_stand();
  bool try_neural_roll_to_stand();
  void load_continuous_rolling();
  void configure_continuous_rolling_io();
  void try_continuous_rolling();

  /* ----------------- Layer sizes ----------------- */
  // TODO: Could make observation a struct with named fields
  static constexpr int kActionSize = 12;
  static constexpr int kDesiredWorldZIdx = 9;
  static constexpr int kJointPositionIdx = 12;
  static constexpr int kLastActionIdx = kJointPositionIdx + kActionSize;
  static constexpr int kSingleObservationSize = 3              /* base link angular velocity */
                                                + 3            /* projected gravity vector */
                                                + 3            /* x, y, yaw velocity commands */
                                                + 3            /* desired world z in body frame */
                                                + kActionSize  /* joint positions */
                                                + kActionSize; /* previous action */
  static constexpr int kGravityZIndx = 5;  // Index of gravity z component in the observation
  /* ----------------------------------------------- */

  std::shared_ptr<RTNeural::Model<float>> model_;
  CommandEncoding command_encoding_ = CommandEncoding::kRaw;
  std::unique_ptr<CemPhaseController> cem_controller_;
  CemPhaseControllerConfig cem_config_;
  bool use_cem_backend_ = false;

  // Previous body-frame IMU orientation, used to accumulate the bias-free
  // rolling phase from successive fused quaternion samples.
  tf2::Quaternion cem_prev_orientation_;
  bool cem_has_prev_orientation_ = false;

  // Roll-to-stand state machine (CEM backend only).  After rolling, a pitch
  // trigger begins a fast interpolation to the configured standing pose.
  enum class RollToStandState { kRolling, kUnfolding, kStanding };
  RollToStandState roll_to_stand_state_ = RollToStandState::kRolling;
  bool roll_to_stand_prev_in_window_ = false;
  double roll_to_stand_unfold_start_s_ = 0.0;
  std::array<double, kActionSize> roll_to_stand_unfold_start_ctrl_{};

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;
  Params continuous_params_;
  std::shared_ptr<RTNeural::Model<float>> continuous_model_;
  struct RollingCommand {
    double vx = 0.6, yaw = 0.0;
    double received = 0.0;
    bool valid = false;
  };
  static double rolling_clock() {
    return std::chrono::duration<double>(
        std::chrono::steady_clock::now().time_since_epoch()).count();
  }
  realtime_tools::RealtimeBuffer<RollingCommand> rolling_command_buffer_;
  RollingCommand continuous_tick_command_;
  rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr rolling_command_subscriber_;
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr rolling_request_subscriber_;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr rolling_state_publisher_;
  rclcpp::TimerBase::SharedPtr rolling_state_timer_;
  std::atomic_bool continuous_requested_{false};
  // 0 unavailable/inactive, 1 startup, 2 pending, 3 continuous, 4 stop, 5 rejected.
  std::atomic_int continuous_stage_{0};
  bool continuous_active_ = false;
  int continuous_history_ticks_ = 0;
  double continuous_last_tick_ = 0.0, continuous_pitch_ = 0.0;
  double continuous_turn_ = 0.0, continuous_request_started_ = 0.0;
  std::array<float, 720> continuous_candidate_{};
  Params transition_params_;
  std::shared_ptr<RTNeural::Model<float>> transition_model_;
  std::array<double, kActionSize> transition_rate_limits_{};
  double transition_timestep_s_ = 0.02;
  double transition_elapsed_s_ = 0.0;
  bool transition_active_ = false;
  std::atomic_bool transition_requested_{false};
  std::atomic_bool rolling_policy_ready_{false};
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr transition_subscriber_;

  // Observation vector. Size is determined at runtime by the observation history parameter
  std::vector<float> observation_ = {};

  // Action vector
  std::array<float, kActionSize> action_ = {};

  // Initial joint positions
  std::array<double, kActionSize> init_joint_pos_ = {};

  // Command velocities
  float cmd_x_vel_ = 0;
  float cmd_y_vel_ = 0;
  float cmd_yaw_vel_ = 0;

  // Command body orientation
  tf2::Vector3 desired_world_z_in_body_frame_ = tf2::Vector3(0, 0, 1);

  // Map from joint names to command types to command interfaces
  std::map<
      std::string,
      std::map<std::string, std::reference_wrapper<hardware_interface::LoanedCommandInterface>>>
      command_interfaces_map_;

  // Map from joint/sensor names to state types to state interfaces
  std::map<std::string,
           std::map<std::string, std::reference_wrapper<hardware_interface::LoanedStateInterface>>>
      state_interfaces_map_;

  // Realtime buffers for command and emergency stop subscriptions
  realtime_tools::RealtimeBuffer<std::shared_ptr<geometry_msgs::msg::Twist>> rt_cmd_vel_ptr_;
  rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr cmd_vel_subscriber_ = nullptr;

  realtime_tools::RealtimeBuffer<std::shared_ptr<geometry_msgs::msg::Pose>> rt_cmd_pose_ptr_;
  rclcpp::Subscription<geometry_msgs::msg::Pose>::SharedPtr cmd_pose_subscriber_ = nullptr;

  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr emergency_stop_subscriber_ = nullptr;
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr emergency_stop_reset_subscriber_ = nullptr;
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr policy_enable_subscriber_ = nullptr;

  // Alias message types for future improvements
  using ActionMsg = std_msgs::msg::Float32MultiArray;
  using ObservationMsg = std_msgs::msg::Float32MultiArray;

  // Publishers
  std::shared_ptr<realtime_tools::RealtimePublisher<ActionMsg>> rt_policy_output_publisher_ =
      nullptr;
  rclcpp::Publisher<ActionMsg>::SharedPtr policy_output_publisher_ = nullptr;

  std::shared_ptr<realtime_tools::RealtimePublisher<ActionMsg>> rt_position_command_publisher_ =
      nullptr;
  rclcpp::Publisher<ActionMsg>::SharedPtr position_command_publisher_ = nullptr;

  // Observation publisher
  std::shared_ptr<realtime_tools::RealtimePublisher<ObservationMsg>> rt_observation_publisher_ =
      nullptr;
  rclcpp::Publisher<ObservationMsg>::SharedPtr observation_publisher_ = nullptr;

  // IMU latency
  std::shared_ptr<realtime_tools::RealtimePublisher<std_msgs::msg::Float32>>
      rt_imu_latency_publisher_ = nullptr;
  rclcpp::Publisher<std_msgs::msg::Float32>::SharedPtr imu_latency_publisher_ = nullptr;

  // Policy inference time
  std::shared_ptr<realtime_tools::RealtimePublisher<std_msgs::msg::Float32>>
      rt_policy_inference_latency_publisher_ = nullptr;
  rclcpp::Publisher<std_msgs::msg::Float32>::SharedPtr policy_inference_latency_publisher_ =
      nullptr;

  rclcpp::Time init_time_;
  rclcpp::Time policy_enable_time_;

  int repeat_action_counter_;

  std::atomic_bool estop_active_{false};
  std::atomic_bool policy_enable_requested_{false};
  bool policy_enabled_ = false;
  bool waiting_for_policy_enable_logged_ = false;
};

}  // namespace neural_controller
